package vibe.bizplan.bizplan_be_inclass.timetracking.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import vibe.bizplan.bizplan_be_inclass.timetracking.entity.TimeEntry;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

public interface TimeEntryRepository extends JpaRepository<TimeEntry, Long> {

    Optional<TimeEntry> findByEventId(Long eventId);

    boolean existsByEventId(Long eventId);

    List<TimeEntry> findByUserId(Long userId);

    List<TimeEntry> findByUserIdAndCreatedAtBetween(
            Long userId, LocalDateTime start, LocalDateTime end
    );

    List<TimeEntry> findByProjectId(Long projectId);

    List<TimeEntry> findByProjectIdAndBillableTrue(Long projectId);

    @Query("""
        SELECT SUM(t.durationMin / 60.0 * t.rate)
        FROM TimeEntry t
        WHERE t.project.id = :projectId
          AND t.billable = true
          AND t.approvedAt IS NOT NULL
          AND t.createdAt BETWEEN :start AND :end
    """)
    BigDecimal sumBillableAmountByProjectAndPeriod(
            @Param("projectId") Long projectId,
            @Param("start") LocalDateTime start,
            @Param("end") LocalDateTime end
    );

    @Query("""
        SELECT COUNT(t) FROM TimeEntry t
        WHERE t.event IS NOT NULL
          AND t.createdAt BETWEEN :start AND :end
    """)
    long countAutoGeneratedEntries(
            @Param("start") LocalDateTime start,
            @Param("end") LocalDateTime end
    );

    @Query("""
        SELECT t FROM TimeEntry t
        WHERE t.user.id = :userId
          AND t.approvedAt IS NULL
        ORDER BY t.createdAt DESC
    """)
    List<TimeEntry> findUnapprovedByUserId(@Param("userId") Long userId);

    @Query("""
        SELECT SUM(t.durationMin) FROM TimeEntry t
        WHERE t.user.id = :userId
          AND t.createdAt BETWEEN :start AND :end
    """)
    Integer sumDurationByUserAndPeriod(
            @Param("userId") Long userId,
            @Param("start") LocalDateTime start,
            @Param("end") LocalDateTime end
    );
}

